export const lineCharPagetLocalization = {
  en: {
    headTitle: "Performance Analytics",
    headSubtitle: "A visual representation of platform expansion and activity levels",
    "New Users": "New Users",
    "Created Events": "Created Events",
    "User Engagement": "User Engagement",
    count: "Count",
    year: "Year",
    revenue: "Revenue",
    transportation: "Month",
    Jan: "Jan",
    Feb: "Feb",
    Mar: "Mar",
    Apr: "Apr",
    May: "May",
    Jun: "Jun",
    Jul: "Jul",
    Aug: "Aug",
    Sep: "Sep",
    Oct: "Oct",
    Nov: "Nov",
    Dec: "Dec",
  },
  ar: {
    headTitle: "تحليلات الأداء",
    headSubtitle: "تمثيل بصري لتوسع المنصة ومستويات النشاط",
    "New Users": "المستخدمون الجدد",
    "Created Events": "الفعاليات المنشأة",
    "User Engagement": "تفاعل المستخدمين",
    count: "العدد",
    Year: "السنه",
    revenue: "العائد",

    transportation: "الشهر",
    Jan: "يناير",
    Feb: "فبراير",
    Mar: "مارس",
    Apr: "أبريل",
    May: "مايو",
    Jun: "يونيو",
    Jul: "يوليو",
    Aug: "أغسطس",
    Sep: "سبتمبر",
    Oct: "أكتوبر",
    Nov: "نوفمبر",
    Dec: "ديسمبر",
  },
};
