export const sidebarlocalizations = {
  en: {
    admin: "Admin",
    dashboard: "Dashboard",
    manage_team: "Manage Team",
    contacts: "Contacts Information",
    invoices: "Invoices Balances",
    add_user: "Add User",
    calendar: "Calendar",
    faq: "FAQ Page",
    bar_chart: "Bar Chart",
    pie_chart: "Pie Chart",
    line_chart: "Line Chart",
    geo_chart: "Geography Chart",
    admin: "Admin",
  },
  ar: {
    admin: "مدير",
    dashboard: "لوحة التحكم",
    manage_team: "إدارة الفريق",
    contacts: "بيانات التواصل",
    invoices: "الفواتير",
    add_user: "إضافة مستخدم",
    calendar: "التقويم",
    faq: "الأسئلة الشائعة",
    bar_chart: "رسم بياني شريطي",
    pie_chart: "رسم بياني دائري",
    line_chart: "رسم بياني خطي",
    geo_chart: "خريطة جغرافية",
    admin: "مدير",
  },
};
